DROP TABLE NOTICE;
DROP SEQUENCE NOTICE_SEQ;

CREATE SEQUENCE NOTICE_SEQ
MAXVALUE 9999999
NOCACHE
NOCYCLE;

CREATE TABLE NOTICE(
    NNO NUMBER(7) PRIMARY KEY,
    AID VARCHAR2(50) REFERENCES ADMIN(AID),
    NTITLE VARCHAR2(100) NOT NULL,
    NCONTENT VARCHAR2(4000) NOT NULL,
    NHIT NUMBER(7) DEFAULT 0,
    NRDATE DATE DEFAULT SYSDATE);
    
-- 쿼리문
SELECT * FROM NOTICE;

--글쓰기(원글)
INSERT INTO NOTICE (NNO, AID, NTITLE, NCONTENT, NHIT) VALUES 
    (NOTICE_SEQ.NEXTVAL, 'admin', '이용수칙입니다.', '즐겁게 잘 이용하면 됩니다.', 0);

INSERT INTO NOTICE (NNO, AID, NTITLE, NCONTENT, NHIT) VALUES 
    (NOTICE_SEQ.NEXTVAL, 'admin', '반려조의 1일 식사량을 알아보자.', '사실 나도 모르지롱', 0);
    
INSERT INTO NOTICE (NNO, AID, NTITLE, NCONTENT, NHIT) VALUES 
    (NOTICE_SEQ.NEXTVAL, 'admin', '펠렛의 장단점과 펠렛 적응시키기', '앵무새 앞에 두면 됩니다.', 0);    
    

-- 글 갯수
SELECT COUNT(*) FROM NOTICE;

-- 글 목록
SELECT * FROM (SELECT ROWNUM RN, A.* FROM (SELECT * FROM NOTICE ORDER BY NRDATE DESC) A) WHERE RN BETWEEN 4 AND 6;

-- 글 히트수 올리기
UPDATE NOTICE SET NHIT = NHIT + 1 WHERE NNO = 3;

-- NNO로 글 DTO 가져오기
SELECT * FROM NOTICE WHERE NNO = 3;

-- 글 수정하기
UPDATE NOTICE SET NTITLE='바뀐제목', NCONTENT='바뀐내용' WHERE NNO = 1;

-- 글 삭제하기
DELETE FROM NOTICE WHERE NNO = 15;

select * from notice;

commit;
