DROP TABLE ORDERS CASCADE CONSTRAINTS;
DROP SEQUENCE ORDERS_SEQ;

CREATE SEQUENCE ORDERS_SEQ
MAXVALUE 9999999
NOCACHE
NOCYCLE;

CREATE TABLE ORDERS(
    ONO NUMBER(7) PRIMARY KEY,
    MID VARCHAR2(50) REFERENCES MEMBER(MID),
    PNO NUMBER(7) REFERENCES PRODUCTS(PNO),
    OADDRESS VARCHAR2(250) NOT NULL,
    OTEL VARCHAR2(50) NOT NULL,
    CNT NUMBER(7) NOT NULL,
    COST NUMBER(7) NOT NULL,
    OSTATE VARCHAR2(50) DEFAULT '대기중',
    ORDATE DATE DEFAULT SYSDATE);
    
-- 주문서 작성
INSERT INTO ORDERS (ONO, MID, PNO, OADDRESS, OTEL, CNT, COST) VALUES 
    (ORDERS_SEQ.NEXTVAL, 'ccc', '1', '서울시 종로구', '02-2586-4898', 1, 35000);
    
INSERT INTO ORDERS (ONO, MID, PNO, OADDRESS, OTEL, CNT, COST) VALUES 
    (ORDERS_SEQ.NEXTVAL, 'aaa', '2', '서울시 양천구', '02-2586-4898', 1, 15000);
    
INSERT INTO ORDERS (ONO, MID, PNO, OADDRESS, OTEL, CNT, COST) VALUES 
    (ORDERS_SEQ.NEXTVAL, 'ddd', '9', '서울시 종로구', '02-2586-4898', 1, 23000);
    
INSERT INTO ORDERS (ONO, MID, PNO, OADDRESS, OTEL, CNT, COST) VALUES 
    (ORDERS_SEQ.NEXTVAL, 'eee', '8', '서울시 종로구', '02-2586-4898', 1, 21000);    
    
-- 주문서     
SELECT * FROM ORDERS ORDER BY ORDATE DESC;

-- 주문서 갯수(관리자)
SELECT COUNT(*) FROM ORDERS;

-- 고객의 주문서 갯수
SELECT COUNT(*) FROM ORDERS WHERE MID = 'bbb';


-- 페이징 처리 (startrow, endrow) - 관리자가 보는 주문서 리스트
SELECT * FROM (SELECT ROWNUM RN, A.* FROM ( SELECT O.*, M.MADDRESS, M.MTEL, P.PNAME, P.PPHOTO 
    FROM ORDERS O, MEMBER M, PRODUCTS P WHERE O.PNO = P.PNO AND O.MID = M.MID ORDER BY ORDATE, OSTATE) A) WHERE RN BETWEEN 2 AND 4;

-- 페이징 처리(startrow, endrow) - 고객이 주문한 주문서 리스트
SELECT * FROM (SELECT ROWNUM RN, A.* FROM ( SELECT O.*, M.MADDRESS, M.MTEL, P.PNAME, P.PPHOTO 
    FROM ORDERS O, MEMBER M, PRODUCTS P WHERE O.PNO = P.PNO AND O.MID = M.MID AND M.MID='bbb' ORDER BY ORDATE DESC) A) WHERE RN BETWEEN 1 AND 3;
    
-- ONO로 주문서 가져오기
SELECT O.*, M.MADDRESS, M.MTEL, P.PNAME, P.PPHOTO 
    FROM ORDERS O, MEMBER M, PRODUCTS P WHERE O.PNO = P.PNO AND O.MID = M.MID AND ONO=3; 

-- 주문 취소
DELETE FROM ORDERS WHERE ONO = 3;

-- 주문 처리하기(관리자)
UPDATE ORDERS SET OSTATE = '완료' WHERE ONO = 7;

-- 주문 시 재고 감소
UPDATE PRODUCTS SET PCNT = PCNT - 1 WHERE PNO = 7;

-- 취소 시 재고 증가
UPDATE PRODUCTS SET PCNT = PCNT + 1 WHERE PNO = 7;

-- 히트 메뉴 순으로 뽑기
SELECT P.* FROM (SELECT PNO, COUNT(*) FROM ORDERS GROUP BY PNO ORDER BY COUNT(*) DESC) A, PRODUCTS P WHERE A.PNO = P.PNO;

 
SELECT * FROM (SELECT ROWNUM RN, B.* FROM(SELECT P.* FROM (SELECT PNO, COUNT(*) FROM ORDERS GROUP BY PNO ORDER BY COUNT(*) DESC) A, 
    PRODUCTS P WHERE A.PNO = P.PNO) B) WHERE RN BETWEEN 2 AND 3;


    

COMMIT;


    